### PR TITLE
Fix: Source Value for object dataField

### LINKED ISSUE #857: onValueSelected prop's source argument changes based on which dataField value was used for option's query
**Issue Type:**

Enhancement/Bug depending on your view on the issue

**Platform:**

Web

**Description:**

In `<DataSearch />` in the `onValueSelected(_, _, source)` prop the `source` parameter varies based on `dataField` values when you could expect the source to always return the root entity.

**Minimal reproduction of the problem with instructions:**

Sorry, don't know the lib well enough to set up a minimal demo, but here is an example of my usecase which I find to cause unexpected results.

Index
```jsx
[
  { id: '1234', anotherEntity: { id: '4321'} },
]
```
```jsx
<DataSearch 
  dataField={['anotherEntity.id',]}
  onValueSelected={(value, _, source) => {
    // value: '4321'
    // source: { id: '4321'}
  }}
/>
```
```jsx
<DataSearch 
  dataField={['id',]}
  onValueSelected={(value, _, source) => {
    // value: '1234'
    // source: { id: '1234', anotherEntity: { id: '4321'} }
  }}
/>
```

To met it seems that always returning the root entity would make sense. I'm not very fluent with elasticsearch though so I would not know if this was a design choice and if the current behaviour is in fact more convenient for some cases.

It can cause issues when there are multiple sources:
```jsx
<DataSearch 
  dataField={['id', 'anotherEntity.id]}
  onValueSelected={(_, _, source) => {
    // value: '1234'
    // source: { id: '1234', anotherEntity: { id: '4321'} }
  }}
/>
```

You'd need to create a check in order to find out what the source contains. My usecase, in more detail, is that I am trying to use `<DataSearch />` as a means to find and then attach end existing entity into another entity by its `id`. E.g. I'm trying to find an `id` to create a many-to-one relationship. The name for the entity is a level deeper than its id. So when I search the name, the `id` I need won't be returned in the `source` argument.

**Reactivesearch version:** 3.0.0-beta.7

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Anything else:**

### PR DESCRIPTION
**Pull request by jyash97**
https://codesandbox.io/s/y27y53k881

Check this demo, in this the source is `member` object.

If we put dataField as `source.object.key` the source would be `object` because of this [line](https://github.com/appbaseio/reactivecore/blob/master/src/utils/suggestions.js#L78).

So to fix this I am now extracting the source directly from suggestion using the `_id`.

Closes https://github.com/appbaseio/reactivesearch/issues/857

### CODE REVIEW

File: src/utils/suggestions.js [hunk 1]
```diff
@@ -24,7 +24,12 @@ const getSuggestions = (fields, suggestions, currentValue, suggestionProperties
 	let suggestionsList = [];
 	let labelsList = [];
 
-	const populateSuggestionsList = (val, source) => {
+	const getSourceValue = (id) => {
```
Comment (metagrover) [inline src/utils/suggestions.js]: This has a complexity of On^2 ~ given it will be called inside a loop of hits.

File: src/utils/suggestions.js [hunk 2]
```diff
@@ -62,7 +66,7 @@ const getSuggestions = (fields, suggestions, currentValue, suggestionProperties
 		}
 	};
 
-	const parseField = (source, field) => {
+	const parseField = (source, field, id) => {
```
Comment (metagrover) [inline src/utils/suggestions.js]: Please refer the source from here instead of creating a getSourceValue function?

File: src/utils/suggestions.js [hunk 3]
```diff
@@ -98,13 +103,14 @@ const getSuggestions = (fields, suggestions, currentValue, suggestionProperties
 		fields.forEach((field) => {
 			parseField(
 				{
-					...item._source,
+					...getSourceValue(_id),
```
Comment (metagrover) [inline src/utils/suggestions.js]: Please do not use `getSourceValue` function here ~ On^2.

**Review by metagrover — CHANGES_REQUESTED** [review]
Please do this implementation directly using the params values instead of finding and attaching the correct values of _source via `getSourceValue`.

**Review by lakhansamani — APPROVED** [review]

**Comment by jyash97** [comment]
@bietkul If this looks good we can merge this, it will close two issues on RS

**Review by bietkul — APPROVED** [review]
